require('dotenv').config();

let PORT = process.env.PORT;
let EMAIL_HOST = process.env.EMAIL_HOST;
let EMAIL_PORT = process.env.EMAIL_PORT;
let EMAIL_USERNAME = process.env.EMAIL_USERNAME ;
let EMAIL_PASSWORD = process.env.EMAIL_PASSWORD ;
let NODE_ENV = process.env.NODE_ENV ;
let JWT_SECRET = process.env.JWT_SECRET ;
let JWT_EXPIRES_IN = process.env.JWT_EXPIRES_IN
let MONGODB_URI = process.env.MONGODB_URI ;
let JWT_COOKIE_EXPIRES_IN = process.env.JWT_COOKIE_EXPIRES_IN ;
let VERIFICATION_STRING_LENGTH = process.env.VERIFICATION_STRING_LENGTH ;
let LINK_LENGTH = process.env.LINK_LENGTH ;
let GUEST_USER_ID = process.env.GUEST_USER_ID ;
let LIMITER_HOURS = process.env.LIMITER_HOURS ;
let GUEST_LIMITER_HOURS = process.env.GUEST_LIMITER_HOURS ;
let AUTH_LIMITER_HOURS = process.env.AUTH_LIMITER_HOURS ;


module.exports = {
    PORT,
    MONGODB_URI,
    NODE_ENV,
    JWT_SECRET,
    JWT_EXPIRES_IN,
    EMAIL_HOST,
    EMAIL_PORT,
    EMAIL_USERNAME,
    EMAIL_PASSWORD,
    JWT_COOKIE_EXPIRES_IN,
    VERIFICATION_STRING_LENGTH,
    LINK_LENGTH,
    GUEST_USER_ID,
    AUTH_LIMITER_HOURS,
    GUEST_LIMITER_HOURS,
    LIMITER_HOURS
};